services:
    pomodoro:
        container_name: pomodoro
        image: ghcr.io/ny-randriantsarafara/pomodoro:latest
        restart: unless-stopped
        env_file: .env
        networks:
            - vps-net
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1',
                ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s

networks:
    vps-net:
        external: true
